//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
  career: Career;
  careerConnection: CareerConnection;
  expertise: Expertise;
  expertiseConnection: ExpertiseConnection;
  media: Media;
  mediaConnection: MediaConnection;
  publications: Publications;
  publicationsConnection: PublicationsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryCareerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCareerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CareerFilter>;
};


export type QueryExpertiseArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryExpertiseConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExpertiseFilter>;
};


export type QueryMediaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMediaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MediaFilter>;
};


export type QueryPublicationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPublicationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationsFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
  career?: InputMaybe<CareerFilter>;
  expertise?: InputMaybe<ExpertiseFilter>;
  media?: InputMaybe<MediaFilter>;
  publications?: InputMaybe<PublicationsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Career | Expertise | Media | Publications | Folder;

export type SiteHero = {
  __typename?: 'SiteHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
};

export type SiteAbout = {
  __typename?: 'SiteAbout';
  paragraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  imageCaption?: Maybe<Scalars['String']['output']>;
};

export type SiteContact = {
  __typename?: 'SiteContact';
  phone?: Maybe<Scalars['String']['output']>;
  phoneLink?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  office?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
  consultations?: Maybe<Scalars['String']['output']>;
  formAction?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
};

export type SiteSeo = {
  __typename?: 'SiteSeo';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SiteFooter = {
  __typename?: 'SiteFooter';
  copyright?: Maybe<Scalars['String']['output']>;
  disclaimer?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  hero?: Maybe<SiteHero>;
  about?: Maybe<SiteAbout>;
  contact?: Maybe<SiteContact>;
  seo?: Maybe<SiteSeo>;
  footer?: Maybe<SiteFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type SiteAboutFilter = {
  paragraphs?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
};

export type SiteContactFilter = {
  phone?: InputMaybe<StringFilter>;
  phoneLink?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  office?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
  consultations?: InputMaybe<StringFilter>;
  formAction?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
};

export type SiteSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteFooterFilter = {
  copyright?: InputMaybe<StringFilter>;
  disclaimer?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  hero?: InputMaybe<SiteHeroFilter>;
  about?: InputMaybe<SiteAboutFilter>;
  contact?: InputMaybe<SiteContactFilter>;
  seo?: InputMaybe<SiteSeoFilter>;
  footer?: InputMaybe<SiteFooterFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type CareerItems = {
  __typename?: 'CareerItems';
  year?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Career = Node & Document & {
  __typename?: 'Career';
  subtitle?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<CareerItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CareerItemsFilter = {
  year?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type CareerFilter = {
  subtitle?: InputMaybe<StringFilter>;
  items?: InputMaybe<CareerItemsFilter>;
};

export type CareerConnectionEdges = {
  __typename?: 'CareerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Career>;
};

export type CareerConnection = Connection & {
  __typename?: 'CareerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CareerConnectionEdges>>>;
};

export type ExpertiseItems = {
  __typename?: 'ExpertiseItems';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Expertise = Node & Document & {
  __typename?: 'Expertise';
  subtitle?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<ExpertiseItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ExpertiseItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ExpertiseFilter = {
  subtitle?: InputMaybe<StringFilter>;
  items?: InputMaybe<ExpertiseItemsFilter>;
};

export type ExpertiseConnectionEdges = {
  __typename?: 'ExpertiseConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Expertise>;
};

export type ExpertiseConnection = Connection & {
  __typename?: 'ExpertiseConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ExpertiseConnectionEdges>>>;
};

export type MediaItems = {
  __typename?: 'MediaItems';
  source?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  linkText?: Maybe<Scalars['String']['output']>;
};

export type Media = Node & Document & {
  __typename?: 'Media';
  subtitle?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<MediaItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MediaItemsFilter = {
  source?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  linkText?: InputMaybe<StringFilter>;
};

export type MediaFilter = {
  subtitle?: InputMaybe<StringFilter>;
  items?: InputMaybe<MediaItemsFilter>;
};

export type MediaConnectionEdges = {
  __typename?: 'MediaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Media>;
};

export type MediaConnection = Connection & {
  __typename?: 'MediaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MediaConnectionEdges>>>;
};

export type PublicationsFamilyLawReviewArticles = {
  __typename?: 'PublicationsFamilyLawReviewArticles';
  year?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  journal?: Maybe<Scalars['String']['output']>;
};

export type PublicationsFamilyLawReview = {
  __typename?: 'PublicationsFamilyLawReview';
  description?: Maybe<Scalars['String']['output']>;
  articles?: Maybe<Array<Maybe<PublicationsFamilyLawReviewArticles>>>;
};

export type PublicationsLawInstituteJournalArticles = {
  __typename?: 'PublicationsLawInstituteJournalArticles';
  year?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  journal?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type PublicationsLawInstituteJournal = {
  __typename?: 'PublicationsLawInstituteJournal';
  articles?: Maybe<Array<Maybe<PublicationsLawInstituteJournalArticles>>>;
};

export type PublicationsPodcastsEpisodes = {
  __typename?: 'PublicationsPodcastsEpisodes';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type PublicationsPodcasts = {
  __typename?: 'PublicationsPodcasts';
  description?: Maybe<Scalars['String']['output']>;
  episodes?: Maybe<Array<Maybe<PublicationsPodcastsEpisodes>>>;
};

export type PublicationsNews = {
  __typename?: 'PublicationsNews';
  source?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type Publications = Node & Document & {
  __typename?: 'Publications';
  familyLawReview?: Maybe<PublicationsFamilyLawReview>;
  lawInstituteJournal?: Maybe<PublicationsLawInstituteJournal>;
  podcasts?: Maybe<PublicationsPodcasts>;
  news?: Maybe<Array<Maybe<PublicationsNews>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PublicationsFamilyLawReviewArticlesFilter = {
  year?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  journal?: InputMaybe<StringFilter>;
};

export type PublicationsFamilyLawReviewFilter = {
  description?: InputMaybe<StringFilter>;
  articles?: InputMaybe<PublicationsFamilyLawReviewArticlesFilter>;
};

export type PublicationsLawInstituteJournalArticlesFilter = {
  year?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  journal?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PublicationsLawInstituteJournalFilter = {
  articles?: InputMaybe<PublicationsLawInstituteJournalArticlesFilter>;
};

export type PublicationsPodcastsEpisodesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type PublicationsPodcastsFilter = {
  description?: InputMaybe<StringFilter>;
  episodes?: InputMaybe<PublicationsPodcastsEpisodesFilter>;
};

export type PublicationsNewsFilter = {
  source?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type PublicationsFilter = {
  familyLawReview?: InputMaybe<PublicationsFamilyLawReviewFilter>;
  lawInstituteJournal?: InputMaybe<PublicationsLawInstituteJournalFilter>;
  podcasts?: InputMaybe<PublicationsPodcastsFilter>;
  news?: InputMaybe<PublicationsNewsFilter>;
};

export type PublicationsConnectionEdges = {
  __typename?: 'PublicationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Publications>;
};

export type PublicationsConnection = Connection & {
  __typename?: 'PublicationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PublicationsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
  updateCareer: Career;
  createCareer: Career;
  updateExpertise: Expertise;
  createExpertise: Expertise;
  updateMedia: Media;
  createMedia: Media;
  updatePublications: Publications;
  createPublications: Publications;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateCareerArgs = {
  relativePath: Scalars['String']['input'];
  params: CareerMutation;
};


export type MutationCreateCareerArgs = {
  relativePath: Scalars['String']['input'];
  params: CareerMutation;
};


export type MutationUpdateExpertiseArgs = {
  relativePath: Scalars['String']['input'];
  params: ExpertiseMutation;
};


export type MutationCreateExpertiseArgs = {
  relativePath: Scalars['String']['input'];
  params: ExpertiseMutation;
};


export type MutationUpdateMediaArgs = {
  relativePath: Scalars['String']['input'];
  params: MediaMutation;
};


export type MutationCreateMediaArgs = {
  relativePath: Scalars['String']['input'];
  params: MediaMutation;
};


export type MutationUpdatePublicationsArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationsMutation;
};


export type MutationCreatePublicationsArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationsMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  career?: InputMaybe<CareerMutation>;
  expertise?: InputMaybe<ExpertiseMutation>;
  media?: InputMaybe<MediaMutation>;
  publications?: InputMaybe<PublicationsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
  career?: InputMaybe<CareerMutation>;
  expertise?: InputMaybe<ExpertiseMutation>;
  media?: InputMaybe<MediaMutation>;
  publications?: InputMaybe<PublicationsMutation>;
};

export type SiteHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type SiteAboutMutation = {
  paragraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
};

export type SiteContactMutation = {
  phone?: InputMaybe<Scalars['String']['input']>;
  phoneLink?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  office?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
  consultations?: InputMaybe<Scalars['String']['input']>;
  formAction?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteFooterMutation = {
  copyright?: InputMaybe<Scalars['String']['input']>;
  disclaimer?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  hero?: InputMaybe<SiteHeroMutation>;
  about?: InputMaybe<SiteAboutMutation>;
  contact?: InputMaybe<SiteContactMutation>;
  seo?: InputMaybe<SiteSeoMutation>;
  footer?: InputMaybe<SiteFooterMutation>;
};

export type CareerItemsMutation = {
  year?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type CareerMutation = {
  subtitle?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<CareerItemsMutation>>>;
};

export type ExpertiseItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ExpertiseMutation = {
  subtitle?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<ExpertiseItemsMutation>>>;
};

export type MediaItemsMutation = {
  source?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  linkText?: InputMaybe<Scalars['String']['input']>;
};

export type MediaMutation = {
  subtitle?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<MediaItemsMutation>>>;
};

export type PublicationsFamilyLawReviewArticlesMutation = {
  year?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  journal?: InputMaybe<Scalars['String']['input']>;
};

export type PublicationsFamilyLawReviewMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  articles?: InputMaybe<Array<InputMaybe<PublicationsFamilyLawReviewArticlesMutation>>>;
};

export type PublicationsLawInstituteJournalArticlesMutation = {
  year?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  journal?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PublicationsLawInstituteJournalMutation = {
  articles?: InputMaybe<Array<InputMaybe<PublicationsLawInstituteJournalArticlesMutation>>>;
};

export type PublicationsPodcastsEpisodesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type PublicationsPodcastsMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  episodes?: InputMaybe<Array<InputMaybe<PublicationsPodcastsEpisodesMutation>>>;
};

export type PublicationsNewsMutation = {
  source?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type PublicationsMutation = {
  familyLawReview?: InputMaybe<PublicationsFamilyLawReviewMutation>;
  lawInstituteJournal?: InputMaybe<PublicationsLawInstituteJournalMutation>;
  podcasts?: InputMaybe<PublicationsPodcastsMutation>;
  news?: InputMaybe<Array<InputMaybe<PublicationsNewsMutation>>>;
};

export type SitePartsFragment = { __typename: 'Site', hero?: { __typename: 'SiteHero', eyebrow?: string | null, name?: string | null, subtitle?: string | null, description?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, about?: { __typename: 'SiteAbout', paragraphs?: Array<string | null> | null, imageCaption?: string | null } | null, contact?: { __typename: 'SiteContact', phone?: string | null, phoneLink?: string | null, email?: string | null, office?: string | null, hours?: string | null, consultations?: string | null, formAction?: string | null, pageSubtitle?: string | null } | null, seo?: { __typename: 'SiteSeo', title?: string | null, description?: string | null } | null, footer?: { __typename: 'SiteFooter', copyright?: string | null, disclaimer?: string | null } | null };

export type CareerPartsFragment = { __typename: 'Career', subtitle?: string | null, items?: Array<{ __typename: 'CareerItems', year?: string | null, title?: string | null, description?: string | null } | null> | null };

export type ExpertisePartsFragment = { __typename: 'Expertise', subtitle?: string | null, items?: Array<{ __typename: 'ExpertiseItems', title?: string | null, description?: string | null } | null> | null };

export type MediaPartsFragment = { __typename: 'Media', subtitle?: string | null, items?: Array<{ __typename: 'MediaItems', source?: string | null, title?: string | null, description?: string | null, link?: string | null, linkText?: string | null } | null> | null };

export type PublicationsPartsFragment = { __typename: 'Publications', familyLawReview?: { __typename: 'PublicationsFamilyLawReview', description?: string | null, articles?: Array<{ __typename: 'PublicationsFamilyLawReviewArticles', year?: string | null, title?: string | null, journal?: string | null } | null> | null } | null, lawInstituteJournal?: { __typename: 'PublicationsLawInstituteJournal', articles?: Array<{ __typename: 'PublicationsLawInstituteJournalArticles', year?: string | null, title?: string | null, journal?: string | null, description?: string | null } | null> | null } | null, podcasts?: { __typename: 'PublicationsPodcasts', description?: string | null, episodes?: Array<{ __typename: 'PublicationsPodcastsEpisodes', title?: string | null, description?: string | null, link?: string | null } | null> | null } | null, news?: Array<{ __typename: 'PublicationsNews', source?: string | null, title?: string | null, description?: string | null, link?: string | null } | null> | null };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', eyebrow?: string | null, name?: string | null, subtitle?: string | null, description?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, about?: { __typename: 'SiteAbout', paragraphs?: Array<string | null> | null, imageCaption?: string | null } | null, contact?: { __typename: 'SiteContact', phone?: string | null, phoneLink?: string | null, email?: string | null, office?: string | null, hours?: string | null, consultations?: string | null, formAction?: string | null, pageSubtitle?: string | null } | null, seo?: { __typename: 'SiteSeo', title?: string | null, description?: string | null } | null, footer?: { __typename: 'SiteFooter', copyright?: string | null, disclaimer?: string | null } | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', eyebrow?: string | null, name?: string | null, subtitle?: string | null, description?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, about?: { __typename: 'SiteAbout', paragraphs?: Array<string | null> | null, imageCaption?: string | null } | null, contact?: { __typename: 'SiteContact', phone?: string | null, phoneLink?: string | null, email?: string | null, office?: string | null, hours?: string | null, consultations?: string | null, formAction?: string | null, pageSubtitle?: string | null } | null, seo?: { __typename: 'SiteSeo', title?: string | null, description?: string | null } | null, footer?: { __typename: 'SiteFooter', copyright?: string | null, disclaimer?: string | null } | null } | null } | null> | null } };

export type CareerQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CareerQuery = { __typename?: 'Query', career: { __typename: 'Career', id: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CareerItems', year?: string | null, title?: string | null, description?: string | null } | null> | null } };

export type CareerConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CareerFilter>;
}>;


export type CareerConnectionQuery = { __typename?: 'Query', careerConnection: { __typename?: 'CareerConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CareerConnectionEdges', cursor: string, node?: { __typename: 'Career', id: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CareerItems', year?: string | null, title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type ExpertiseQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ExpertiseQuery = { __typename?: 'Query', expertise: { __typename: 'Expertise', id: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ExpertiseItems', title?: string | null, description?: string | null } | null> | null } };

export type ExpertiseConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExpertiseFilter>;
}>;


export type ExpertiseConnectionQuery = { __typename?: 'Query', expertiseConnection: { __typename?: 'ExpertiseConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ExpertiseConnectionEdges', cursor: string, node?: { __typename: 'Expertise', id: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ExpertiseItems', title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type MediaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MediaQuery = { __typename?: 'Query', media: { __typename: 'Media', id: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'MediaItems', source?: string | null, title?: string | null, description?: string | null, link?: string | null, linkText?: string | null } | null> | null } };

export type MediaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MediaFilter>;
}>;


export type MediaConnectionQuery = { __typename?: 'Query', mediaConnection: { __typename?: 'MediaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MediaConnectionEdges', cursor: string, node?: { __typename: 'Media', id: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'MediaItems', source?: string | null, title?: string | null, description?: string | null, link?: string | null, linkText?: string | null } | null> | null } | null } | null> | null } };

export type PublicationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PublicationsQuery = { __typename?: 'Query', publications: { __typename: 'Publications', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, familyLawReview?: { __typename: 'PublicationsFamilyLawReview', description?: string | null, articles?: Array<{ __typename: 'PublicationsFamilyLawReviewArticles', year?: string | null, title?: string | null, journal?: string | null } | null> | null } | null, lawInstituteJournal?: { __typename: 'PublicationsLawInstituteJournal', articles?: Array<{ __typename: 'PublicationsLawInstituteJournalArticles', year?: string | null, title?: string | null, journal?: string | null, description?: string | null } | null> | null } | null, podcasts?: { __typename: 'PublicationsPodcasts', description?: string | null, episodes?: Array<{ __typename: 'PublicationsPodcastsEpisodes', title?: string | null, description?: string | null, link?: string | null } | null> | null } | null, news?: Array<{ __typename: 'PublicationsNews', source?: string | null, title?: string | null, description?: string | null, link?: string | null } | null> | null } };

export type PublicationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationsFilter>;
}>;


export type PublicationsConnectionQuery = { __typename?: 'Query', publicationsConnection: { __typename?: 'PublicationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PublicationsConnectionEdges', cursor: string, node?: { __typename: 'Publications', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, familyLawReview?: { __typename: 'PublicationsFamilyLawReview', description?: string | null, articles?: Array<{ __typename: 'PublicationsFamilyLawReviewArticles', year?: string | null, title?: string | null, journal?: string | null } | null> | null } | null, lawInstituteJournal?: { __typename: 'PublicationsLawInstituteJournal', articles?: Array<{ __typename: 'PublicationsLawInstituteJournalArticles', year?: string | null, title?: string | null, journal?: string | null, description?: string | null } | null> | null } | null, podcasts?: { __typename: 'PublicationsPodcasts', description?: string | null, episodes?: Array<{ __typename: 'PublicationsPodcastsEpisodes', title?: string | null, description?: string | null, link?: string | null } | null> | null } | null, news?: Array<{ __typename: 'PublicationsNews', source?: string | null, title?: string | null, description?: string | null, link?: string | null } | null> | null } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  hero {
    __typename
    eyebrow
    name
    subtitle
    description
    ctaText
    ctaLink
  }
  about {
    __typename
    paragraphs
    imageCaption
  }
  contact {
    __typename
    phone
    phoneLink
    email
    office
    hours
    consultations
    formAction
    pageSubtitle
  }
  seo {
    __typename
    title
    description
  }
  footer {
    __typename
    copyright
    disclaimer
  }
}
    `;
export const CareerPartsFragmentDoc = gql`
    fragment CareerParts on Career {
  __typename
  subtitle
  items {
    __typename
    year
    title
    description
  }
}
    `;
export const ExpertisePartsFragmentDoc = gql`
    fragment ExpertiseParts on Expertise {
  __typename
  subtitle
  items {
    __typename
    title
    description
  }
}
    `;
export const MediaPartsFragmentDoc = gql`
    fragment MediaParts on Media {
  __typename
  subtitle
  items {
    __typename
    source
    title
    description
    link
    linkText
  }
}
    `;
export const PublicationsPartsFragmentDoc = gql`
    fragment PublicationsParts on Publications {
  __typename
  familyLawReview {
    __typename
    description
    articles {
      __typename
      year
      title
      journal
    }
  }
  lawInstituteJournal {
    __typename
    articles {
      __typename
      year
      title
      journal
      description
    }
  }
  podcasts {
    __typename
    description
    episodes {
      __typename
      title
      description
      link
    }
  }
  news {
    __typename
    source
    title
    description
    link
  }
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const CareerDocument = gql`
    query career($relativePath: String!) {
  career(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CareerParts
  }
}
    ${CareerPartsFragmentDoc}`;
export const CareerConnectionDocument = gql`
    query careerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CareerFilter) {
  careerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CareerParts
      }
    }
  }
}
    ${CareerPartsFragmentDoc}`;
export const ExpertiseDocument = gql`
    query expertise($relativePath: String!) {
  expertise(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ExpertiseParts
  }
}
    ${ExpertisePartsFragmentDoc}`;
export const ExpertiseConnectionDocument = gql`
    query expertiseConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ExpertiseFilter) {
  expertiseConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ExpertiseParts
      }
    }
  }
}
    ${ExpertisePartsFragmentDoc}`;
export const MediaDocument = gql`
    query media($relativePath: String!) {
  media(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MediaParts
  }
}
    ${MediaPartsFragmentDoc}`;
export const MediaConnectionDocument = gql`
    query mediaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MediaFilter) {
  mediaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MediaParts
      }
    }
  }
}
    ${MediaPartsFragmentDoc}`;
export const PublicationsDocument = gql`
    query publications($relativePath: String!) {
  publications(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PublicationsParts
  }
}
    ${PublicationsPartsFragmentDoc}`;
export const PublicationsConnectionDocument = gql`
    query publicationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PublicationsFilter) {
  publicationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PublicationsParts
      }
    }
  }
}
    ${PublicationsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    career(variables: CareerQueryVariables, options?: C): Promise<{data: CareerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerQueryVariables, query: string}> {
        return requester<{data: CareerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerQueryVariables, query: string}, CareerQueryVariables>(CareerDocument, variables, options);
      },
    careerConnection(variables?: CareerConnectionQueryVariables, options?: C): Promise<{data: CareerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerConnectionQueryVariables, query: string}> {
        return requester<{data: CareerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerConnectionQueryVariables, query: string}, CareerConnectionQueryVariables>(CareerConnectionDocument, variables, options);
      },
    expertise(variables: ExpertiseQueryVariables, options?: C): Promise<{data: ExpertiseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExpertiseQueryVariables, query: string}> {
        return requester<{data: ExpertiseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExpertiseQueryVariables, query: string}, ExpertiseQueryVariables>(ExpertiseDocument, variables, options);
      },
    expertiseConnection(variables?: ExpertiseConnectionQueryVariables, options?: C): Promise<{data: ExpertiseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExpertiseConnectionQueryVariables, query: string}> {
        return requester<{data: ExpertiseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExpertiseConnectionQueryVariables, query: string}, ExpertiseConnectionQueryVariables>(ExpertiseConnectionDocument, variables, options);
      },
    media(variables: MediaQueryVariables, options?: C): Promise<{data: MediaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaQueryVariables, query: string}> {
        return requester<{data: MediaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaQueryVariables, query: string}, MediaQueryVariables>(MediaDocument, variables, options);
      },
    mediaConnection(variables?: MediaConnectionQueryVariables, options?: C): Promise<{data: MediaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaConnectionQueryVariables, query: string}> {
        return requester<{data: MediaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MediaConnectionQueryVariables, query: string}, MediaConnectionQueryVariables>(MediaConnectionDocument, variables, options);
      },
    publications(variables: PublicationsQueryVariables, options?: C): Promise<{data: PublicationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsQueryVariables, query: string}> {
        return requester<{data: PublicationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsQueryVariables, query: string}, PublicationsQueryVariables>(PublicationsDocument, variables, options);
      },
    publicationsConnection(variables?: PublicationsConnectionQueryVariables, options?: C): Promise<{data: PublicationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsConnectionQueryVariables, query: string}> {
        return requester<{data: PublicationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsConnectionQueryVariables, query: string}, PublicationsConnectionQueryVariables>(PublicationsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  